### ISSUE TITLE
Problem with saving attachment from OST file

### ISSUE THREAD

**Issue by Elimas** [rjohnsondev/java-libpst#47]
Welcome I have problem with saving attachment from OST file.
The saved file is corrupted and the size of file is 64 KB, the original file size is 646 KB.
I created example on github with this OST file: https://github.com/Elimas/OST-reading-problem
Here is the OST file (200 mb): [OST file](https://drive.google.com/file/d/0B9IhzCgxFPr9VWV5T2hydmFleWM/view?usp=sharing) please copy it to **src/main/resources/email.ost**.
Here is the original file **ocr2_original** and file saved by library **ocr2_saved**.
[files.zip](https://github.com/rjohnsondev/java-libpst/files/368663/files.zip)
I think that this can be caused by big file size or by that this file was placed in reply to message.
Some attachments are saved correctly and some not (ocr2.pdf, ocr3.pdf, ocr4.pdf)
I opened the OST file in Kernel OST Viewer and was able to save this attachment correctly.

**Comment by rjohnsondev** [comment]
Thank you so much for providing an example OST file, it is disproportionately difficult for me to create these.

I've had a look over it all and I think I've managed to fix the issue, would you be able to give the code that's in the develop branch a go and let me know if you run into any additional problems?

Thanks again,

Richard

**Comment by Elimas** [comment]
Thank You
I downloaded the develop branch and it seems that files are saved correctly but there are problems with other messages. Please try to save all attachments from provided OST file. (You can peek OST file in Kernel OST Viewer).
I get lots of errors like (in attach.getFileInputStream()):
`com.pff.PSTException: Unable to compress reportedly compressed block
	at com.pff.PSTNodeInputStream.detectZlib(PSTNodeInputStream.java:154)
	at com.pff.PSTNodeInputStream.<init>(PSTNodeInputStream.java:95)
	at com.pff.PSTAttachment.getFileInputStream(PSTAttachment.java:123)
	at com.company.Main.saveAttachments(Main.java:75)
	at com.company.Main.processFolder(Main.java:55)
	at com.company.Main.processFolder(Main.java:44)
	at com.company.Main.processFolder(Main.java:44)
	at com.company.Main.processFolder(Main.java:44)
	at com.company.Main.testOst(Main.java:23)
	at com.company.Main.main(Main.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.util.zip.ZipException: incorrect header check
	at java.util.zip.InflaterOutputStream.write(InflaterOutputStream.java:273)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at com.pff.PSTNodeInputStream.detectZlib(PSTNodeInputStream.java:130)
	... 14 more`

**Comment by rjohnsondev** [comment]
Ugh, that's frustrating, sorry.  Try now?

**Comment by Elimas** [comment]
It now works really well.
Thank You.
