### ISSUE TITLE
java.io.UnsupportedEncodingException: ISO-8859-8-I

### ISSUE THREAD

**Issue by 7UpMan** [rjohnsondev/java-libpst#57]
Hi I am processing a 200,000 mail archive a somewhere between 149,000 and 150,000 I got the exception:

`Unable to decode string
java.io.UnsupportedEncodingException: ISO-8859-8-I
	at java.lang.StringCoding.decode(StringCoding.java:190)
	at java.lang.String.<init>(String.java:426)
	at java.lang.String.<init>(String.java:491)
	at com.pff.PSTObject.createJavaString(PSTObject.java:327)
	at com.pff.PSTObject.getStringItem(PSTObject.java:300)
	at com.pff.PSTMessage.getBodyHTML(PSTMessage.java:717)
	at com.s4apps.mailIndex.S4Folder.storeMessage(S4Folder.java:218)
	at com.s4apps.mailIndex.S4Folder.processItems(S4Folder.java:203)
	at com.s4apps.mailIndex.S4Folder.store(S4Folder.java:77)
	at com.s4apps.mailIndex.S4Folder.store(S4Folder.java:82)
	at com.s4apps.mailIndex.S4Folder.store(S4Folder.java:82)
	at processemail.ProcessEmail.<init>(ProcessEmail.java:80)
	at processemail.ProcessEmail.main(ProcessEmail.java:56)`

The last line of my code reads `String bodyTextHtml = msg.getBodyHTML();`

The program then went on to completion.

Tracking down the exact item is possible, but rather time consuming.

Thanks

PS - I use NetBeans as the IDE and it grabbed the code from Git. Version: 0.9.5-SNAPSHOT

PPS - love the library, fantastic work.

**Comment by rjohnsondev** [comment]
Can you check with the 0.9.4 version and see if that also exhibits the
issue?

**Comment by 7UpMan** [comment]
Will do.  I will run it over night and get back to you.

**Comment by 7UpMan** [comment]
I re-ran the test as requested and all ok.  I will close this issue.

Thanks.

**Comment by rjohnsondev** [comment]
Just checking, did the problem exist in 0.9.5-snapshot but not is 0.9.4? I ask because there was some encoding stuff changed, and it's possible a bug was introduced....

**Comment by 7UpMan** [comment]
You are correct.  Everything was fine in 0.9.4 but the exception occurred in 0.9.5-snapshot.  It was 1 record out of 200,000.  I was going to re-run tonight with the 0.9.5-snapshot and see if it is consistent.

Let me know if you have any other things you would like me to try.

**Comment by rjohnsondev** [comment]
cool, going to re-open then; it's probably a quick fix

**Comment by 7UpMan** [comment]
I re-ran the test with 0.9.5-snapshot and it failed at the same point.  200,000 rows and 1 failure.

What would you like to do next?

**Comment by rjohnsondev** [comment]
Cool, that's great to know; I'll try to get a fix in place this weekend!

**Comment by 7UpMan** [comment]
If you are having a dig around in the code I also get a: 

`Can't get children for folder 2014(33570) child count: 33486 - java.lang.ArrayIndexOutOfBoundsException: 47, using alternate child tree with 33486 items`

This seems to be more of a warning than an error.

I also get lots of different unknown message types which don't seem to affect anything:

-  IPM.Note.Rules.OofTemplate.Microsoft
-  IPM.Note.StorageQuotaWarning
-  REPORT.IPM.Note.NDR
-  REPORT.IPM.Note.IPNRN
-  IPM.Note.SpamReportForm_136E441
-  REPORT.IPM.Note.DR
-  REPORT.IPM.Schedule.Meeting.Request.NDR
-  IPM.Sharing
-  REPORT.IPM.Schedule.Meeting.Resp.Neg.NDR
-  IPM.Recall.Report.Success
-  REPORT.IPM.Outlook.Recall.NDR
-  IPM.Recall.Report.Failure
-  IPM
-  REPORT.IPM.Note.IPNNRN
-  IPM.Document.FoxitReader.Document
-  IPM.TaskRequest
-  IPM.Note.Rules.ReplyTemplate.Microsoft
-  IPM.Note.Rules.ExternalOofTemplate.Microsoft
-  REPORT.REPORT.IPM.Note.IPNRN.NDR
-  IPM.Post
-  REPORT.IPM.Note.Delayed.DR
-  IPM.Note.NotSupportedICal
-  REPORT.IPM.Schedule.Meeting.Canceled.NDR
-  IPM.Note.StorageQuotaWarning.Warning
-  IPM.Note.Mobile.SMS
