### ISSUE TITLE
com.pff.PSTException: Unknown child type with offset id: 0

### ISSUE THREAD

**Issue by ballamartin** [rjohnsondev/java-libpst#65]
Hello, 
I am using the latest build 0.9.5 with Office 2013 OST Files and everytime after reading some content successfully i get this error:

```
com.pff.PSTException: Unknown child type with offset id: 0
	at com.pff.PSTObject.detectAndLoadPSTObject(PSTObject.java:761)
	at com.pff.PSTFolder.getNextChild(PSTFolder.java:306)
```
I also scan my files with Scanpst.exe and correct some errors, but that makes no difference. 
The maven test are passed successfully.

Do you have any ideas?

Greetings, 
Martin

**Comment by maximevdk** [comment]
Did you find a solution to this exception?
I've a similar exception only when using multiple threads.

**Comment by ballamartin** [comment]
No. 
I haven't found a solution to the problem except for catching and ignoring the error messages and continue with the next node. 
I use a recursive crawler pattern to scan all objects inside the pst/ost files. I dont use multiple threads.
